### ISSUE TITLE
Generated secret side-effects are cleaned up when put in the generatedSecretsDir path.

### ISSUE THREAD

**Issue by Faeranne** [oddlama/agenix-rekey#44]
I'm attempting to generate a wireguard public and private key file, and due to the layout, need to use the generatedSecretsDir path for it.  The issue is, generated side-effect files, like the public key, get cleared out if the `rekeyFile` attribute is set to `generatedSecretsDir` or a subdirectory of that.  Setting `rekeyFile` to anywhere else in the flake directory doesn't cause this issue.

Is there any way to recover this, either by having an option to disable the orphan cleanup, or by getting it to recognize these side-effect files?

for reference, I'm using the wireguard generator listed in the readme, exactly as written:
```nix
{
  age.generators.wireguard-priv = {pkgs, file, ...}: ''
    priv=$(${pkgs.wireguard-tools}/bin/wg genkey)
    ${pkgs.wireguard-tools}/bin/wg pubkey <<< "$priv" > ${lib.escapeShellArg (lib.removeSuffix ".age" file + ".pub")}
    echo "$priv"
  '';
}
```

**Comment by oddlama** [comment]
Currently i fear there's no option to disable any of that logic. The idea of the `generatedSecretsDir` was that it will only ever contain things known to the generators so there's a clear boundary where the automatic cleanup knows it is safe to delete anything within. Although I wouldn't be opposed to refine this behavior to just consider deletion of `.age` files for example.

For the time being, I'm not sure why you require the files to be in the `generatedSecretsDir` though. You could work around it by placing the files in a separate folder. I've also placed all my wireguard related files in a `secrets/wireguard/<net>` folder separate from the `secrets/generated/<host>` folder which then also allows grouping the secrets by the wireguard network instead of the hostname first. Might be important if you want to have pre-shared keys as they require you to identify the same secret for each 2-tuple of hostnames ([example](https://github.com/oddlama/nixos-extra-modules/blob/2dfcc1f7de2cb36566c5f1b48986dd4555a173dc/modules/wireguard.nix#L188-L212)).

**Comment by Faeranne** [comment]
I will check soon as I have my computer booted.  Main reason for this is that I am separating concerns, and in doing so, some secret handling logic is ending up in a separate flake.  Because of that, and a preference to keep things reusable, I don't necessarily have access to the calling flake's path, nor any guarantee that there is a `secrets` folder.  Only guarenteeing that the generated secrets directory is set. (by simply not setting rekeyFile, and letting the logic fail through to agenix-rekey.)

**Comment by Faeranne** [comment]
This does seem to resolve the issue.

**Comment by oddlama** [comment]
Perfect!
